version: "3"

services:
  todosDB:
    image: postgres:15.3
    container_name: todos-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
  cloudbeaver:
    image: dbeaver/cloudbeaver:${APP_VERSION}
    container_name: "${APP_NAME}"
    restart: always
    ports:
      - "$APP_HTTP_PORT:8978"
    volumes:
      - ./cloudbeaver:/opt/cloudbeaver/workspace
